x-common-variables: &common-env
  KAFKA_S3_ACCESS_KEY: amin
  KAFKA_S3_SECRET_KEY: admin
  KAFKA_HEAP_OPTS: -Xms1g -Xmx4g -XX:MetaspaceSize=96m -XX:MaxDirectMemorySize=1G
  # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
  CLUSTER_ID: 5XF4fHIOTfSIqkmje2KFlg

services:
  # spark-iceberg:
  #   image: tabulario/spark-iceberg
  #   container_name: spark-iceberg
  #   build: spark/
  #   networks:
  #     iceberg_net:
  #   depends_on:
  #     - rest
  #     - minio
  #   volumes:
  #     - ./warehouse:/home/iceberg/warehouse
  #     - ./notebooks:/home/iceberg/notebooks/notebooks
  #   environment:
  #     - AWS_ACCESS_KEY_ID=admin
  #     - AWS_SECRET_ACCESS_KEY=password
  #     - AWS_REGION=us-east-1
  #   ports:
  #     - 8888:8888
  #     - 8080:8080
  #     - 10000:10000
  #     - 10001:10001
  rest:
    image: docker.arvancloud.ir/apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: docker.arvancloud.ir/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: docker.arvancloud.ir/minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;

      #AutoMQ bucket
      /usr/bin/mc rm -r --force minio/automq-data;
      /usr/bin/mc mb minio/automq-data;
      /usr/bin/mc policy set public minio/automq-data;

      /usr/bin/mc rm -r --force minio/automq-ops;
      /usr/bin/mc mb minio/automq-ops;
      /usr/bin/mc policy set public minio/automq-ops;

      tail -f /dev/null
      "
  automq:
    image: docker.arvancloud.ir/automqinc/automq:1.6.0
    container_name: automq
    environment:
      CLUSTER_ID: "7tP7oJ7vTg2qkVPHczs3FA"
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password123
    volumes:
      - ./server.properties:/opt/automq/kafka/config/kraft/server.properties
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on: [minio, mc, rest]


networks:
  iceberg_net:

volumes:
  minio:
    driver: local
