
x-common-variables: &common-env
  KAFKA_S3_ACCESS_KEY: minioadmin
  KAFKA_S3_SECRET_KEY: minioadmin
  KAFKA_HEAP_OPTS: -Xms1g -Xmx4g -XX:MetaspaceSize=96m -XX:MaxDirectMemorySize=1G
  # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
  CLUSTER_ID: 5XF4fHIOTfSIqkmje2KFlg

services:
  # MinIO service for S3 storage
  minio:
    container_name: "minio"
    image: docker.arvancloud.ir/minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      automq_net:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3

  # Create needed buckets
  mc:
    container_name: "mc"
    image: docker.arvancloud.ir/minio/minio:latest 
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/automq-data;
      /usr/bin/mc rm -r --force minio/automq-ops;
      /usr/bin/mc mb minio/automq-data;
      /usr/bin/mc mb minio/automq-ops;
      /usr/bin/mc anonymous set public minio/automq-data;
      /usr/bin/mc anonymous set public minio/automq-ops;
      tail -f /dev/null
      "
    networks:
      - automq_net

  # Three nodes for AutoMQ cluster
  server1:
    container_name: "automq-server1"
    image: docker.arvancloud.ir/automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$$CLUSTER_ID \
        --override node.id=0 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server1:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true'
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

  server2:
    container_name: "automq-server2"
    image: docker.arvancloud.ir/automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$$CLUSTER_ID \
        --override node.id=1 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server2:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true'
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

  server3:
    container_name: "automq-server3"
    image: docker.arvancloud.ir/automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$$CLUSTER_ID \
        --override node.id=2 \
        --override controller.quorum.voters=0@server1:9093,1@server2:9093,2@server3:9093 \
        --override controller.quorum.bootstrap.servers=server1:9093,server2:9093,server3:9093 \
        --override advertised.listeners=PLAINTEXT://server3:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true'
    networks:
      automq_net:
    depends_on:
      - minio
      - mc

networks:
  automq_net:
    name: automq_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.6.0.0/16"
          gateway: "10.6.0.1"